name: Test Go TDD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      BROKER_ADDR: ${{ secrets.BROKER_ADDR_SECRET }}
      HIVE_USER: ${{ secrets.HIVE_PSWD_SECRET }}
      HIVE_PSWD: ${{ secrets.HIVE_USER_SECRET }}

    defaults:
      run:
        shell: bash
        working-directory: "./src/"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Get dependencies
        run: go mod tidy

      - name: Creating enviroment variables
        working-directory: src/pkg/
        run: 
          touch .env
          echo "BROKER_ADDRT=${{ secrets.BROKER_ADDR_SECRET }}" >> .env
          echo "HIVE_USER=${{ secrets.HIVE_PSWD_SECRET }}" >> .env
          echo "HIVE_PWSD=${{ secrets.HIVE_USER_SECRET }}" >> .env
          tree

      - name: Test client
        working-directory: src/tests/
        run: 
          go test -v --cover client_test.go
      
      - name: Test controller
        working-directory: src/tests/
        run:  
          go test -v --cover controller_test.go

      - name: Teste unitário sensor de gases
        working-directory: src/internal/mics6814/
        run:  
          go test -v --cover mics6814_test.go

      - name: Teste unitário sensor de radiação
        working-directory: src/internal/rxwlib900/
        run:  
          go test -v --cover rxwlib900_test.go
      

