name: Test Go TDD

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    # env: 
    #   BROKER_ADDR_SECRET: ${{ secrets.BROKER_ADDR_SECRET }}
    #   HIVE_USER_SECRET: ${{ secrets.HIVE_PSWD_SECRET }}
    #   HIVE_PWSD_SECRET: ${{ secrets.HIVE_USER_SECRET }}

    defaults:
      run:
        shell: bash
        working-directory: "./src/"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Get dependencies
        run: go mod tidy

      - name: Create .env
        working-directory: src/pkg/commom/
        run: 
          touch .env
          echo "BROKER_ADDR_SECRET=${{ secrets.BROKER_ADDR_SECRET }}" >> .env
          echo "HIVE_USER_SECRET=${{ secrets.HIVE_PSWD_SECRET }}" >> .env
          echo "HIVE_PWSD_SECRET=${{ secrets.HIVE_USER_SECRET }}" >> .env

      - name: Test client
        run: | 
          cd tests
          go test -v --cover client_test.go
      
      - name: Test controller
        run: | 
          go test -v --cover controller_test.go
      
      # - name: Test API do banco de dados
      #   run: | 
      #     go test -v --cover api_db_test.go

      - name: Teste unitário sensor de gases
        run: | 
          cd ../internal/mics6814/
          go test -v --cover mics6814_test.go

      - name: Teste unitário sensor de radiação
        run: | 
          cd ../rxwlib900/
          go test -v --cover rxwlib900_test.go
      

